------WHICH PRODUCT HAS BEEN SOLD MORE THAN THE COUNTRY WISE AVG VALUE USING WITH CLAUSE

select * from Book8

WITH ABC AS
(
SELECT A.*,B.AVG_QTY 
FROM BOOK8 AS A
LEFT JOIN
(
SELECT COUNTRY,AVG(QTY) AS AVG_QTY
FROM BOOK8
GROUP BY COUNTRY
) AS B
ON A.COUNTRY=B.COUNTRY
)
, ABC2 AS
(
SELECT *,CASE WHEN QTY>AVG_QTY THEN 'YES' ELSE 'NO' END AS STATUS 
FROM ABC
)
SELECT * FROM ABC2
WHERE STATUS='YES'

-- WHICH PRODUCT HAS BEEN SOLD LESS THAN COUNTRY WISE 50% TOTAL VALUE.
with abc as
(
select A.*, B.total_qty
from Book8 as A
left Join
(
select country, (0.5 * sum(qty)) as total_qty
from Book8
group by COUNTRY
) as B
on a.COUNTRY = b.COUNTRY
), abc2 as 
(
select *, case when qty < total_qty then 'yes' else 'no' end as STATUS
from abc
)

select * from abc2
where STATUS = 'yes'



--WHICH PRODUCT HAS BEEN SOLD MORE THAN THE COUNTRY WISE AVG VALUE USING SUB QUERY

SELECT D.* FROM
(
SELECT C.*,CASE WHEN C.QTY>C.AVG_QTY THEN 'YES' ELSE 'NO' END AS STATUS
FROM
(
SELECT A.*,B.AVG_QTY
FROM BOOK8 AS A
LEFT JOIN
(
SELECT COUNTRY,AVG(QTY) AS AVG_QTY
FROM BOOK8
GROUP BY COUNTRY
) AS B
ON A.COUNTRY=B.COUNTRY
) AS C
) AS D




