WITH ABC AS
(
SELECT *,1 AS KEYYY FROM SALES_AVG
)
, ABC2 AS
(
SELECT 1 AS KEYYY,AVG(SALE) AS AVG_SALE
FROM SALES_AVG
)
, ABC3 AS
(SELECT A.COUNTRY,A.PRODUCT,A.SALE,B.AVG_SALE
FROM ABC AS A
LEFT JOIN ABC2 AS B
ON A.KEYYY=B.KEYYY
)
SELECT * FROM ABC3
WHERE SALE>AVG_SALE